import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {SERVICES} from './services.mjs';import {connectionStore,listConnections,prepareConnection,connectionAction,resolveConnectionEnv,safeUrl,requireUiWrite,ConnectionError} from './connections.mjs';import {genericCall,clean} from './generic.mjs';
function database(){const db=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('./drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('./drizzle/'+f,import.meta.url),'utf8'));return {prepare(sql){const stmt=db.prepare(sql);return {bind(...args){return {async run(){return {meta:{changes:Number(stmt.run(...args).changes)}};},async first(){return stmt.get(...args)||null;},async all(){return {results:stmt.all(...args)}}};},async all(){return {results:stmt.all()}}};}};}
const base=()=>({DB:database(),COOKIEJAR_ENABLED:'true',HUB_KEY:'FAKE_HOSTED_COOKIEJAR'});
const draft={id:'example_api',name:'Example API',baseUrl:'https://api.example.com/v1',authHeader:'X-API-Key',authPrefix:'',description:'Example service',accessDescription:'Use the API you request.',sourceUrl:'https://example.com/docs',keyHelpUrl:'https://example.com/account/keys',testRequest:{method:'GET',path:'/health'}};
async function connection(env,id='example_api'){return (await listConnections(env)).connections.find(c=>c.id===id);}
const success=async()=>Response.json({ok:true});
test('prepared connection stores no key and does not make a network call',async()=>{const env=base();const r=await prepareConnection(draft,env);assert.equal(r.prepared,true);const row=await connectionStore(env.DB).get(draft.id,true);assert.equal(row.key_value,null);assert.equal((await connection(env)).status,'needs_key');await assert.rejects(async()=>genericCall('bridge_api_read',{serviceId:draft.id,method:'GET',path:'/items'},await resolveConnectionEnv(env),success));});
test('key save binds origin/header and makes arbitrary documented paths usable without endpoint mappings',async()=>{const env=base();await prepareConnection(draft,env);const c=await connection(env);const saved=await connectionAction(c.id,'key',{key:'FAKE_SAVED_KEY',expectedBinding:c.binding,test:true},env,async(url,init)=>{assert.equal(url,'https://api.example.com/v1/health');assert.equal(init.headers.get('X-API-Key'),'FAKE_SAVED_KEY');assert.equal(init.headers.get('Authorization'),null);return Response.json({ok:true});});assert.equal(saved.connection.status,'ready');assert.ok(!JSON.stringify(saved).includes('FAKE_SAVED_KEY'));const resolved=await resolveConnectionEnv(env);const result=await genericCall('bridge_api_read',{serviceId:c.id,method:'GET',path:'/unmapped/resource',query:{page:2}},resolved,async(url,init)=>{assert.equal(url,'https://api.example.com/v1/unmapped/resource?page=2');assert.equal(init.headers.get('X-API-Key'),'FAKE_SAVED_KEY');return Response.json({value:'works'});});assert.equal(result.bodyJson.value,'works');});
test('metadata-only listing does not return saved key, fragments, or hosted key',async()=>{const env=base();await prepareConnection({...draft,testRequest:undefined},env);const c=await connection(env);await connectionAction(c.id,'key',{key:'FAKE_SAVED_KEY',expectedBinding:c.binding},env,success);const status=await listConnections(env);assert.ok(!JSON.stringify(status).includes('FAKE_SAVED_KEY'));assert.ok(!JSON.stringify(status).includes(env.HUB_KEY));assert.equal(status.connections.find(c=>c.id==='cookiejar').source,'hosted');});
test('built-in saved key replaces env only after explicit save; disconnect suppresses fallback',async()=>{const env=base();const c=await connection(env,'cookiejar');assert.equal((await resolveConnectionEnv(env)).HUB_KEY,env.HUB_KEY);await connectionAction('cookiejar','key',{key:'FAKE_REPLACEMENT',expectedBinding:c.binding,test:false},env,success);assert.equal((await resolveConnectionEnv(env)).HUB_KEY,'FAKE_REPLACEMENT');const ready=await connection(env,'cookiejar');await connectionAction('cookiejar','disconnect',{expectedBinding:ready.binding},env,success);const resolved=await resolveConnectionEnv(env);assert.equal(resolved.HUB_KEY,undefined);assert.equal(resolved.__BRIDGE_SERVICES.cookiejar.enabled,false);assert.equal(env.HUB_KEY,'FAKE_HOSTED_COOKIEJAR');assert.equal((await connection(env,'cookiejar')).status,'disabled');assert.equal((await connectionStore(env.DB).get('cookiejar',true)).key_value,null);});
test('failed key check leaves prior working key unchanged and never echoes rejected value',async()=>{const env=base();await prepareConnection(draft,env);let c=await connection(env);await connectionAction(c.id,'key',{key:'FAKE_OLD_KEY',expectedBinding:c.binding,test:false},env,success);c=await connection(env);await assert.rejects(()=>connectionAction(c.id,'key',{key:'FAKE_BAD_KEY',expectedBinding:c.binding},env,async()=>Response.json({token:'FAKE_BAD_KEY'},{status:401})),e=>e.status===422&&!e.message.includes('FAKE_BAD_KEY'));assert.equal((await connectionStore(env.DB).get(c.id,true)).key_value,'FAKE_OLD_KEY');});
test('built-in destination cannot be retargeted and stale binding cannot save',async()=>{const env=base();await assert.rejects(()=>prepareConnection({...draft,id:'cookiejar'},env));await prepareConnection(draft,env);const c=await connection(env);await assert.rejects(()=>prepareConnection({...draft,baseUrl:'https://other.example.com'},env));await assert.rejects(()=>connectionAction(c.id,'key',{key:'FAKE_KEY',expectedBinding:'stale'},env,success),e=>e.status===409);});
test('a slow key check cannot reactivate a later disconnect',async()=>{const env=base();await prepareConnection(draft,env);const c=await connection(env);let release;const gate=new Promise(r=>release=r);let started;const start=new Promise(r=>started=r);const save=connectionAction(c.id,'key',{key:'FAKE_SLOW_KEY',expectedBinding:c.binding},env,async()=>{started();await gate;return Response.json({ok:true});});await start;await connectionAction(c.id,'disconnect',{expectedBinding:c.binding},env,success);release();await assert.rejects(()=>save,e=>e.status===409);assert.equal((await connection(env)).status,'disabled');assert.equal((await connectionStore(env.DB).get(c.id,true)).key_value,null);});
test('storage errors fail closed rather than silently falling back',async()=>{const env=base();const broken={async listMeta(){throw Error('D1 unavailable')}};await assert.rejects(()=>resolveConnectionEnv(env,broken));await assert.rejects(()=>listConnections(env,broken));});
test('public HTTPS destination/header guards reject SSRF, secret URLs and reserved IDs',async()=>{for(const value of ['https://localhost.','https://metadata.google.internal.','https://127.1','https://2130706433','https://0x7f000001','https://[::1]','https://10.0.0.1','https://api.example.com:8443','http://api.example.com','https://user:password@api.example.com','https://api.example.com?key=secret'])assert.throws(()=>safeUrl(value,{base:true}),value);for(const authHeader of ['Host','Cookie','Origin','X-Forwarded-Host','Proxy-Authorization','Sec-Fetch-Site','Content-Length','bad\r\nHeader'])await assert.rejects(()=>prepareConnection({...draft,authHeader},base()));for(const id of ['constructor','__proto__',['constructor']])await assert.rejects(()=>prepareConnection({...draft,id},base()));});
test('UI mutations require same Origin, real JSON and custom UI header',()=>{const make=(headers={},method='POST')=>new Request('https://bridge.example.com/api/connections/example/key',{method,headers});const good={Origin:'https://bridge.example.com','Content-Type':'application/json','X-Bridge-UI':'1','Sec-Fetch-Site':'same-origin'};assert.doesNotThrow(()=>requireUiWrite(make(good)));for(const change of [{Origin:'https://evil.example.com'},{Origin:''},{'X-Bridge-UI':''},{'Content-Type':'application/jsonp'},{'Sec-Fetch-Site':'cross-site'}])assert.throws(()=>requireUiWrite(make({...good,...change})));assert.throws(()=>requireUiWrite(make(good,'GET')));});
test('configured-key reflections in JSON property names and values are redacted',()=>{const key='FAKE_SAVED_KEY';assert.ok(!JSON.stringify(clean({[key]:key,nested:{['prefix-'+key]:'x'}},[key])).includes(key));});

import {createHandler} from './worker.mjs';
function uiRequest(path,{method='GET',body,auth=true,headers={}}={}){return new Request('https://bridge.example.com'+path,{method,headers:{...(auth?{'oai-authenticated-user-id':'test-user'}:{}),...(method==='POST'?{'content-type':'application/json',origin:'https://bridge.example.com','x-bridge-ui':'1'}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});}
test('private setup page and status require managed authentication; page has no-store nonce CSP',async()=>{const env=base(),h=createHandler(success);for(const path of ['/','/api/connections'])assert.equal((await h(uiRequest(path,{auth:false}),env)).status,403);const response=await h(uiRequest('/'),env),html=await response.text();assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');assert.match(response.headers.get('content-security-policy'),/script-src 'nonce-/);assert.ok(html.includes('data-bridge-script nonce='));assert.ok(!html.includes(env.HUB_KEY));const meta=await(await h(uiRequest('/api/connections'),env)).text();assert.ok(!meta.includes(env.HUB_KEY));});
test('same-origin UI save uses stored key in subsequent MCP reads and returns no key',async()=>{const env=base();let lastAuth;const h=createHandler(async(u,o)=>{lastAuth=o.headers.get('Authorization');return Response.json({siteId:'fixture',token:'provider-secret'});});const status=await(await h(uiRequest('/api/connections'),env)).json();const c=status.connections.find(c=>c.id==='cookiejar');const save=await h(uiRequest('/api/connections/cookiejar/key',{method:'POST',body:{key:'FAKE_UI_KEY',expectedBinding:c.binding,test:true}}),env);assert.equal(save.status,200);assert.ok(!(await save.text()).includes('FAKE_UI_KEY'));const request=new Request('https://bridge.example.com/mcp',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':'test-user'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'bridge_api_read',arguments:{serviceId:'cookiejar',method:'GET',path:'/me'}}})});assert.equal((await h(request,env)).status,200);assert.equal(lastAuth,'Bearer FAKE_UI_KEY');});
test('cross-origin UI and browser-simple MCP requests fail before any mutation or provider call',async()=>{const env=base();let n=0;const h=createHandler(()=>{n++;});for(const headers of [{origin:'https://evil.example.com'},{origin:''},{'x-bridge-ui':''},{'content-type':'application/jsonp'}])assert.equal((await h(uiRequest('/api/connections/prepare',{method:'POST',body:draft,headers}),env)).status,403);const mcp=type=>new Request('https://bridge.example.com/mcp',{method:'POST',headers:{'content-type':type,origin:'https://evil.example.com','oai-authenticated-user-id':'test-user'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'bridge_prepare_connection',arguments:draft}})});assert.equal((await h(mcp('text/plain; application/json'),env)).status,415);assert.equal((await h(mcp('application/json'),env)).status,403);assert.equal((await connectionStore(env.DB).listMeta()).length,0);assert.equal(n,0);});
test('agent can prepare non-secret draft without runtime settings, but cannot pass a key',async()=>{const env={...base()};const h=createHandler(()=>{throw Error('No network expected')});const req=args=>new Request('https://bridge.example.com/mcp',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':'test-user'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'bridge_prepare_connection',arguments:args}})});assert.equal((await(await h(req(draft),env)).json()).result.isError,false);assert.equal((await(await h(req({...draft,key:'FAKE_FORBIDDEN'}),env)).json()).error.code,-32602);assert.equal((await connectionStore(env.DB).get(draft.id,true)).key_value,null);});
test('save diagnostics distinguish input, provider HTTP, network and response failures without secret echo',async()=>{
 for(const [code,key,fetcher,http] of [
  ['key_format','FAKE WITH SPACE',success,null],
  ['provider_rejected','FAKE_DIAGNOSTIC_KEY',async()=>new Response('FAKE_DIAGNOSTIC_KEY',{status:401}),401],
  ['provider_http','FAKE_DIAGNOSTIC_KEY',async()=>new Response('FAKE_DIAGNOSTIC_KEY',{status:503}),503],
  ['provider_redirect','FAKE_DIAGNOSTIC_KEY',async()=>new Response(null,{status:302}),302],
  ['provider_network','FAKE_DIAGNOSTIC_KEY',async()=>{throw Error('FAKE_DIAGNOSTIC_KEY');},null],
  ['provider_response','FAKE_DIAGNOSTIC_KEY',async()=>new Response(new ReadableStream({start(c){c.error(Error('FAKE_DIAGNOSTIC_KEY'));}})),null]
 ]){
  const env=base(),c=await connection(env,'cookiejar'),handler=createHandler(fetcher);
  const response=await handler(uiRequest('/api/connections/cookiejar/key',{method:'POST',body:{key,expectedBinding:c.binding}}),env);
  const body=await response.json();assert.equal(body.code,code);assert.equal(body.providerStatus,http);assert(!JSON.stringify(body).includes(key));assert.equal((await connectionStore(env.DB).listMeta()).length,0);
 }
});
test('save diagnostics identify configuration and storage failures without provider bodies or key values',async()=>{
 const env=base();await prepareConnection({...draft,testRequest:{method:'GET',path:'/login'}},env);let calls=0;const c=await connection(env);
 await assert.rejects(connectionAction(c.id,'key',{key:'FAKE_DIAGNOSTIC_KEY',expectedBinding:c.binding},env,async()=>{calls++;return Response.json({});}),e=>e.code==='check_configuration');assert.equal(calls,0);
 const realPrepare=env.DB.prepare;env.DB.prepare=(sql)=>{if(sql.startsWith('INSERT INTO bridge_connections'))throw Error('FAKE_STORAGE_DETAIL');return realPrepare(sql);};
 const builtin=await connection(env,'cookiejar');const response=await createHandler(success)(uiRequest('/api/connections/cookiejar/key',{method:'POST',body:{key:'FAKE_DIAGNOSTIC_KEY',expectedBinding:builtin.binding}}),env);const body=await response.json();assert.equal(response.status,503);assert.equal(body.code,'storage_unavailable');assert(!JSON.stringify(body).includes('FAKE_'));
});
test('saved Cookiejar and RPC connections work with an otherwise empty environment, including durable writes',async()=>{
 const old={...base(),EXAMPLE_RPC_ENABLED:'true',EXAMPLE_RPC_API_URL:'https://rpc.example.com',EXAMPLE_RPC_KEY:'FAKE_HOSTED_RPC'};
 for(const id of ['cookiejar','example_rpc']){const c=await connection(old,id);await connectionAction(id,'key',{key:'FAKE_SAVED_'+id,expectedBinding:c.binding},old,success);}
 const empty={DB:old.DB};assert((await listConnections(empty)).connections.every(c=>c.source==='saved'));
 const resolved=await resolveConnectionEnv(empty);let calls=0;
 const fetcher=async(url,init)=>{calls++;assert(url.startsWith('https://rpc.example.com/')||url.startsWith(SERVICES.cookiejar.baseUrl));assert(!url.includes('undefined'));assert.equal(init.headers.get(url.startsWith('https://rpc.')?'X-Example-Key':'Authorization'),url.startsWith('https://rpc.')?'FAKE_SAVED_example_rpc':'Bearer FAKE_SAVED_cookiejar');return Response.json({ok:true});};
 for(const [serviceId,method,path,bodyJson] of [['cookiejar','GET','/sites',undefined],['example_rpc','POST','/',{action:'list_records'}]])assert.equal((await genericCall('bridge_api_read',{serviceId,method,path,...(bodyJson?{bodyJson}:{})},resolved,fetcher)).status,200);
 const h=createHandler(fetcher),request=(name,args)=>new Request('https://bridge.example.com/mcp',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':'test-user'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})});
 for(const [serviceId,path,bodyJson,operationId] of [['cookiejar','/sites',{name:'Mock only'},'12345678-1234-1234-1234-123456789aaa'],['example_rpc','/',{action:'write_record',text:'Mock only'},'12345678-1234-1234-1234-123456789aab']]){const req=()=>request('bridge_api_write',{serviceId,path,method:'POST',bodyJson,operationId});const first=await(await h(req(),empty)).json();assert.equal(JSON.parse(first.result.content[0].text).state,'completed');const replay=await(await h(req(),empty)).json();assert.equal(JSON.parse(replay.result.content[0].text).replayed,true);}
 assert.equal(calls,4);
 // Existing binding cannot be changed even after legacy endpoint settings disappear.
 await assert.rejects(prepareConnection({...draft,id:'example_rpc',authHeader:'X-Example-Key',baseUrl:'https://other.example.com'},empty));
 // Saved settings, not a later environment endpoint, remain authoritative.
 const changed=await resolveConnectionEnv({...empty,EXAMPLE_RPC_API_URL:'https://other.example.com'});assert.equal(changed.__BRIDGE_SERVICES.example_rpc.baseUrl,'https://rpc.example.com');
});
test('fresh installation needs only the D1 binding and owner key entry, with no environment settings',async()=>{
 const env={DB:database()};const initial=await listConnections(env);assert.equal(initial.storageAvailable,true);assert.equal(initial.connections.length,1);assert.equal(initial.connections[0].id,'cookiejar');assert.equal(initial.connections[0].status,'needs_key');
 const h=createHandler(async(url,init)=>{assert.equal(url,SERVICES.cookiejar.baseUrl+'/sites');assert.equal(init.headers.get('Authorization'),'Bearer FAKE_FIRST_RUN');return Response.json({sites:[]});});
 const page=await h(uiRequest('/'),env);assert.equal(page.status,200);assert((await page.text()).includes('What do you want to connect?'));
 const response=await h(uiRequest('/api/connections/cookiejar/key',{method:'POST',body:{key:'FAKE_FIRST_RUN',expectedBinding:initial.connections[0].binding}}),env);assert.equal(response.status,200);const body=await response.json();assert.equal(body.connection.source,'saved');assert.equal(body.connection.status,'ready');assert(!JSON.stringify(body).includes('FAKE_FIRST_RUN'));assert.deepEqual(Object.keys(env),['DB']);
});
