import {test} from 'node:test';import assert from 'node:assert/strict';import {genericCall,prepare,clean} from './generic.mjs';import {createHandler} from './worker.mjs';
const env={COOKIEJAR_ENABLED:'true',HUB_KEY:'DUMMY_COOKIEJAR_SECRET',OWNER_USER_ID:'owner',WRITES_ENABLED:'true',PROJECT_TREE_ENABLED:'true',PROJECT_TREE_INGEST_TOKEN:'DUMMY_TREE_SECRET'};const id='12345678-1234-1234-1234-123456789abc';const read={serviceId:'cookiejar',method:'GET',path:'/me',siteId:'example-site'};
function ledger(){const rows=new Map();return {rows,async get(k){return rows.get(k)},async claim(k,f){if(rows.has(k))return false;rows.set(k,{fingerprint:f,state:'in_progress'});return true;},async set(k,s,r){Object.assign(rows.get(k),{state:s,result:JSON.stringify(r)});}}}
test('generic GET/HEAD uses fixed service auth and allows only safe headers',async()=>{for(const method of ['GET','HEAD']){const r=await genericCall('bridge_api_read',{...read,method,headers:{Accept:'application/json'}},env,async(u,o)=>{assert.equal(u,'https://cookiejar-api.example.invalid/me');assert.equal(o.headers.get('Authorization'),'Bearer '+env.HUB_KEY);assert.equal(o.headers.get('X-Site'),'example-site');assert.equal(o.redirect,'manual');return Response.json({ok:true});});assert.equal(r.status,200);}});
test('SSRF/traversal/origin/query/header injection and credential routes rejected',()=>{for(const path of ['https://evil.invalid','//evil.invalid','/../key','/%2e%2e/key','/%252e/key','/a\\b','/x?target=evil','/x#evil','/key','/env','/sites/x/rotate','/admin/sites','/v1/auth','/sites/x/env'])assert.throws(()=>prepare({...read,path},env));for(const header of ['Authorization','X-Site','Host','Cookie','Proxy-Authorization','X-Forwarded-Host'])assert.throws(()=>prepare({...read,headers:{[header]:'bad'}},env));assert.throws(()=>prepare({...read,query:{token:'secret'}},env));});
test('all generic write methods use durable ledger and never retry',async()=>{for(const method of ['POST','PUT','PATCH','DELETE']){let n=0;const l=ledger(),args={serviceId:'cookiejar',method,path:'/c/test/item',siteId:'s1',operationId:id,bodyJson:{value:'approved'}};const f=async(u,o)=>{n++;assert.equal(o.method,method);return Response.json({ok:true});};assert.equal((await genericCall('bridge_api_write',args,env,f,l)).state,'completed');assert.equal((await genericCall('bridge_api_write',args,env,f,l)).replayed,true);assert.equal(n,1);await assert.rejects(()=>genericCall('bridge_api_write',{...args,path:'/c/other/item'},env,f,l));}});
test('network uncertainty and HTTP500 persist reconciliation, never replay mutation',async()=>{for(const failure of ['network','500']){let n=0;const l=ledger(),args={serviceId:'cookiejar',method:'POST',path:'/sites',bodyJson:{name:'Requested'},operationId:id};const f=async()=>{n++;if(failure==='network')throw Error(env.HUB_KEY);return Response.json({error:env.HUB_KEY},{status:500});};const r=await genericCall('bridge_api_write',args,env,f,l);assert.equal(r.state,'needs_reconciliation');await genericCall('bridge_api_write',args,env,f,l);assert.equal(n,1);assert.ok(!JSON.stringify([...l.rows.values()]).includes(env.HUB_KEY));}});
test('credential response fields and exact configured secrets are redacted before storage',async()=>{const l=ledger();const r=await genericCall('bridge_api_write',{serviceId:'cookiejar',method:'POST',path:'/sites',bodyJson:{name:'Requested'},operationId:id},env,async()=>Response.json({siteId:'s',token:'new token',nested:{secretAccessKey:'new credential',text:env.HUB_KEY}}),l);assert.equal(r.result.response.bodyJson.token,'[REDACTED]');assert.equal(r.result.response.bodyJson.nested.secretAccessKey,'[REDACTED]');assert.ok(!JSON.stringify([...l.rows.values()]).includes('new token'));});
test('JSON/text/base64 request bodies supported with strict exclusivity and bounds',()=>{assert.equal(prepare({...read,method:'POST',bodyText:'hello'},env).requestBody,'hello');assert.equal(prepare({...read,method:'PUT',bodyBase64:btoa('hello')},env).requestBody.length,5);assert.throws(()=>prepare({...read,method:'POST',bodyText:'a',bodyJson:{}},env));assert.throws(()=>prepare({...read,method:'POST',bodyText:'x'.repeat(524289)},env));assert.throws(()=>prepare({...read,method:'POST',bodyJson:{nested:{apiKey:'bad'}}},env));});
test('redirect never followed and binary or oversized responses handled safely',async()=>{let n=0;const redirect=await genericCall('bridge_api_read',read,env,async()=>{n++;return new Response(null,{status:302,headers:{Location:'https://evil.invalid'}});});assert.equal(redirect.redirectRefused,true);assert.equal(n,1);const binary=await genericCall('bridge_api_read',read,env,async()=>new Response(new Uint8Array([1,2,3]),{headers:{'content-type':'application/octet-stream'}}));assert.equal(binary.bodyBase64,'AQID');await assert.rejects(()=>genericCall('bridge_api_read',read,env,async()=>new Response('x'.repeat(524289))));await assert.rejects(()=>genericCall('bridge_api_read',read,env,async()=>new Response(env.HUB_KEY,{headers:{'content-type':'application/octet-stream'}})));});
test('ProjectTree disabled by default, uses its own token after configured',async()=>{const a={serviceId:'projecttree',method:'POST',path:'/',bodyJson:{action:'tree'}};await assert.rejects(()=>genericCall('bridge_api_read',a,{HUB_KEY:'cookie-only'},()=>{throw Error('must not call')}));const r=await genericCall('bridge_api_read',a,env,async(u,o)=>{assert.equal(u,'https://project-tree-api.example.invalid/');assert.equal(o.headers.get('x-ingest-token'),env.PROJECT_TREE_INGEST_TOKEN);assert.equal(o.headers.get('Authorization'),null);return Response.json({ok:true,nodes:[]});});assert.equal(r.bodyJson.ok,true);});
test('ProjectTree read POST action allowlist excludes mutation and credential actions',async()=>{for(const action of ['write','mailread','issue','mapkey','voice','speak','UNKNOWN'])await assert.rejects(()=>genericCall('bridge_api_read',{serviceId:'projecttree',method:'POST',path:'/',bodyJson:{action}},env,()=>{throw Error('must not call')}));assert.throws(()=>prepare({serviceId:'projecttree',method:'POST',path:'/',bodyJson:{action:'submit',sourceUrl:'https://evil.invalid'}},env));});
test('preview does not call upstream or grant approval',async()=>{const r=await genericCall('bridge_api_preview',{serviceId:'cookiejar',method:'DELETE',path:'/c/test/item'},env,()=>{throw Error('must not call')});assert.equal(r.method,'DELETE');assert.match(r.approval,/does not authorize/);});
test('owner required and unknown arguments blocked for generic tools',async()=>{let n=0;const h=createHandler(()=>{n++});const request=(user,args)=>new Request('https://bridge.invalid/mcp',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':user},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'bridge_api_read',arguments:args}})});assert.equal((await h(request('intruder',read),env)).status,403);const j=await(await h(request('owner',{...read,apiKey:'forbidden'}),env)).json();assert.equal(j.error.code,-32602);assert.equal(n,0);});

test('generic operation status reads durable state without external calls',async()=>{const l=ledger();await l.claim(id,'fingerprint');await l.set(id,'needs_reconciliation',{notice:'inspect upstream'});const r=await genericCall('bridge_operation_status',{operationId:id},env,()=>{throw Error('must not call')},l);assert.equal(r.state,'needs_reconciliation');});
